FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_API_URL
ARG VITE_BACKEND_URL

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

RUN npm run build

CMD ["sh", "-c", "rm -rf /srv/frontend/* && cp -r /app/dist/* /srv/frontend/ && echo 'Frontend build copied to /srv/frontend' && tail -f /dev/null"]
