server {
    listen 8080;
    server_name _;

    root /app/public;
    index index.php;

    client_max_body_size 20M;

    # API Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Storage publico
    location /storage {
        alias /app/storage/app/public;
        expires 30d;
        access_log off;
        try_files $uri =404;
    }

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 300;
    }

    # No exponer archivos ocultos
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
